---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: ["http://elasticsearch:9200"]
monitoring.ui.container.elasticsearch.enabled: false

## X-Pack security credentials

elasticsearch.username: elastic
elasticsearch.password: changeme
#elasticsearch.ssl.certificateAuthorities: "/usr/share/kibana/config/elasticsearch-ca.pem"
#elasticsearch.ssl.verificationMode: none

#xpack.encryptedSavedObjects.encryptionKey: jlkaj29iopashajlseomby7238galkja
